name: fastml4jets
channels:
  - conda-forge
  - defaults
  - pip
dependencies:
  - python=3.10
  - root>6.40
  - pip
  - pip:
      - numpy==1.26.4
      - tensorflow==2.14.1
      - keras==2.14.0
      - keras-tuner==1.4.8
      - qkeras
      - awkward
      - matplotlib
      - scikit-learn
      - pyarrow
      - pandas
      - uproot
      - vector
      - ipykernel
      - xgboost
      - scikit-image
      - pre-commit
      - jupyterlab
      - hls4ml
      - fastjet
      - numba
      - mplhep
      - statsmodels
